name: Windows Build Generation

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Generate for Windows and push to the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "mavka-ukr/mavka-windows"
          path: "mavka-windows"
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_WINDOWS }}
          persist-credentials: true
      - run: |
          export MAVKA_VERSION="$(cat ВЕРСІЯ)"
          export GIT_LATEST_COMMIT_HASH="$(git rev-parse --short HEAD)"
          wget https://github.com/tsil-ukr/files/raw/main/випуски-цілі/0.32.0/ціль-0.32.0-x86_64-linux-gnu.zip
          unzip ціль-0.32.0-x86_64-linux-gnu.zip
          rm -rf mavka-windows/.плавлення
          rm -rf mavka-windows/external
          rm -rf mavka-windows/README.md
          bash скрипти/згенерувати_для_будування_на_windows.sh ціль-0.32.0-x86_64-linux-gnu/ціль
          cd mavka-windows
          git config --local user.name "kohutd"
          git config --local user.email "davyd.kohut@gmail.com"
          git add .
          git commit -m "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          git tag "$MAVKA_VERSION-$GIT_LATEST_COMMIT_HASH"
          cd -
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          tags: true
          directory: "mavka-windows"
          repository: "mavka-ukr/mavka-windows"
          ssh: true
          github_token: ${{ secrets.SSH_DEPLOY_KEY_MAVKA_WINDOWS }}